### ISSUE TITLE
[Bug] After selecting all and pressing delete on the keyboard, the editor can no longer function.

### ISSUE THREAD

**Issue by hkm5558** [AppFlowy-IO/appflowy-editor#1001]
### Bug Description

When double-tap the text, select "Select All" from the toolbar that appears, and then click "Delete,",  the editor can no longer function. The official demo can reproduce this problem.

```
Flutter Error Caught: Invalid argument(s): 0 
 StackTrace: #0      int.clamp (dart:core-patch/integers.dart:280:7)
         #1      EditorStateSelection._findCloseNode (package:appflowy_editor/src/editor/editor_component/service/selection/shared.dart:98:16)
         #2      EditorStateSelection.getNodeInOffset (package:appflowy_editor/src/editor/editor_component/service/selection/shared.dart:41:15)
         #3      _MobileSelectionServiceWidgetState.getNodeInOffset (package:appflowy_editor/src/editor/editor_component/service/selection/mobile_selection_service.dart:364:24)
         #4      _MobileSelectionServiceWidgetState._onTapUpIOS (package:appflowy_editor/src/editor/editor_component/service/selection/mobile_selection_service.dart:585:20)
         #5      MobileSelectionGestureDetectorState._tapDownDelegate (package:appflowy_editor/src/service/selection/mobile_selection_gesture.dart:119:24)
         #6      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:653:57)
         #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
```

### How to Reproduce

When running the demo project on iOS, if you double-tap the text, select "Select All" from the toolbar that appears, and then click "Delete," the following error will be reported. The official demo can reproduce this problem.

### Expected Behavior

We hope to delete the content normally without errors, ensuring the editor functions properly.

### Operating System

iOS

### AppFlowy Editor Version(s)

4.0.0

**Comment by MichalNemec** [comment]
also happening on web platform

**Comment by hbedford** [comment]
with me is the same thing happening on web
