### ISSUE TITLE
[Bug]  Cannot type on empty document in latest changes 

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#138]
### Bug Description

https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/8b28068b-5888-41b7-8cc7-a540ed84e11a

### How to Reproduce

Select empty document from drawer 

### Expected Behavior

You should be able to start editing text but not working 

### Operating System

Macos,

### AppFlowy Editor Version(s)

Main branch Code

### Screenshots

<img width="1309" alt="Screenshot 2023-05-29 at 11 05 56 AM" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/b5d1950c-77ab-4485-bf0d-f0427db472d1">
same behaviour on macos

**Comment by alihassan143** [comment]
@LucasXu0

**Comment by alihassan143** [comment]
```
When the exception was thrown, this was the stack:
#0      LinkedList._insertBefore (dart:collection/linked_list.dart:193:7)
#1      LinkedList.add (dart:collection/linked_list.dart:97:5)
#2      Iterable.forEach (dart:core/iterable.dart:346:35)
#3      LinkedList.addAll (dart:collection/linked_list.dart:102:13)
#4      new Node (package:appflowy_editor/src/core/document/node.dart:29:13)
#5      new Document.empty (package:appflowy_editor/src/core/document/document.dart:28:18)
#6      new EditorState.empty (package:appflowy_editor/src/editor_state.dart:63:30)
#7      _HomePageState._buildDrawer.<anonymous closure> (package:example/home_page.dart:102:38)
#8      _HomePageState._buildListTile.<anonymous closure> (package:example/home_page.dart:201:16)
#9      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)
#14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:465:19)
#21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:445:22)
#22     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:331:11)
#23     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400:7)
#24     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363:5)
#25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
#26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
#27     _invoke1 (dart:ui/hooks.dart:158:13)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
```
**When Adding Empty Document**

**Comment by LucasXu0** [comment]
the `document.empty` is deprecated. use `document.blank` instead.

**Comment by LucasXu0** [comment]
I added a new constructor.

```dart
EditorState.blank(withInitialText: true)
```

**Comment by annieappflowy** [comment]
@alihassan143 , is this resolved?

**Comment by LucasXu0** [comment]
Hi, @asadamatic. There will be a lot of hint text if all the paragraphs are empty without the focus logic? Are you sure that this is your expectation?

**Comment by asadamatic** [comment]
@LucasXu0 I thought that hint text is particular to a document, not a paragraph. For a blank document, I would want the hint to appear even without focus. If the hint text is not visible there's no way for the user to know that theirs an editor. 

I can go with a workaround, but I think it makes sense to have some sort of indicator for empty documents (without focus).

**Comment by LucasXu0** [comment]
I suggest you can make a stack or something to show the hint text when the document is empty.
