### ISSUE TITLE
[Bug] Empty Document withInitialText creates bad document

### ISSUE THREAD

**Issue by nigeltiany** [AppFlowy-IO/appflowy-editor#165]
### Bug Description

Creating an editor state from a blank document leads to a malformed document

### How to Reproduce

```dart
editorState = EditorState(
  document: persistedDoc.isEmpty ? Document.blank(withInitialText: true) : Document.fromJson(persistedDoc),
  editable: true,
);

return AppFlowyEditor.standard(
  editable: true,
  autoFocus: true,
  editorState: editorState,
);
```

when `autoFocus` is set to true and `withInitialText` set to false, an error is thrown

```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for PropertyValueNotifier<Selection?>:
'package:appflowy_editor/src/editor/editor_component/service/selection/desktop_selection_service.dart': Failed assertion: line 496 pos 14: 'false': is not true.

When the exception was thrown, this was the stack: 
#2      _DesktopSelectionServiceWidgetState._updateCursorAreas (package:appflowy_editor/src/editor/editor_component/service/selection/desktop_selection_service.dart:496:14)
#3      _DesktopSelectionServiceWidgetState._updateSelection.updateSelection (package:appflowy_editor/src/editor/editor_component/service/selection/desktop_selection_service.dart:176:11)
#4      _DesktopSelectionServiceWidgetState._updateSelection (package:appflowy_editor/src/editor/editor_component/service/selection/desktop_selection_service.dart:186:7)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#6      PropertyValueNotifier.value= (package:appflowy_editor/src/editor/util/property_notifier.dart:25:5)
#7      EditorState.selection= (package:appflowy_editor/src/editor_state.dart:92:23)
#8      EditorState.updateSelectionWithReason (package:appflowy_editor/src/editor_state.dart:167:10)
#9      _AppFlowyEditorState._autoFocusIfNeeded (package:appflowy_editor/src/service/editor_service.dart:224:19)
```

1) set `autoFocus` and  `withInitialText` to true

2) type a `/` character and select `H1` then type a few characters

3) persist this document and refresh the page/app

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building PageBlockComponent-[GlobalKey#0a670](dirty):
node(heading) is invalid, attributes: {level: 1.0, delta: [{insert: This file is NOT okay}]}, children: []
'package:appflowy_editor/src/editor/editor_component/service/renderer/block_component_service.dart':
Failed assertion: line 95 pos 9: 'false'

The relevant error-causing widget was: 
  AppFlowyEditor AppFlowyEditor:file:///...
When the exception was thrown, this was the stack: 
#2      BlockComponentRenderer.build (package:appflowy_editor/src/editor/editor_component/service/renderer/block_component_service.dart:95:9)
#3      BlockComponentRendererService.buildList.<anonymous closure> (package:appflowy_editor/src/editor/editor_component/service/renderer/block_component_service.dart:68:24)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#6      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162:27)
#7      new _List.of (dart:core-patch/array.dart:127:20)
#8      new List.of (dart:core-patch/array_patch.dart:49:20)
#9      ListIterable.toList (dart:_internal/iterable.dart:214:7)
```

Repeating step 1 to 3 and but typing without `/ -> H1` selection at step 2, does NOT throw an error when reloading the saved document

Okay document

```json
{"document": {"type": "page", "children": [{"data": {"delta": [{"insert": "this file is okay"}]}, "type": "paragraph"}]}}
```

Error document

```json
{"document": {"type": "page", "children": [{"data": {"delta": [{"insert": "This file is NOT okay"}], "level": 1}, "type": "heading"}]}}
```

### Expected Behavior

H1 selection should not the error
```

### Operating System

Linux

### AppFlowy Editor Version(s)

1.0.0-dev1

### Screenshots

_No response_

### Additional Context

_No response_

**Comment by nigeltiany** [comment]
Found the issue

```dart
@override
  bool validate(Node node) =>
      node.delta != null &&
      node.children.isEmpty &&
      node.attributes[HeadingBlockKeys.level] is int;
```

My stored json operations convert the level attribute to double.
`1` becomes `1.0`

**Comment by LucasXu0** [comment]
Hi, @nigeltiany. The level must be an integer value. It doesn't make sense to change it to a double or any other numeric type. Otherwise, it could lead to unexpected results if a developer passes a decimal value like 1.1.

**Comment by nigeltiany** [comment]
@LucasXu0 My [PR](https://github.com/AppFlowy-IO/appflowy-editor/pull/166) accounts for this. I have tested setting the level to 1.1 and it does not break things

```dart
-  TextStyle? defaultTextStyle(int level) {
+ TextStyle? defaultTextStyle(num level) {
      final fontSizes = [32.0, 28.0, 24.0, 18.0, 18.0, 18.0];
-     final fontSize = fontSizes.elementAtOrNull(level) ?? 18.0;
+    final fontSize = fontSizes.elementAtOrNull(level.toInt()) ?? 18.0;
```

Anyway, This is editor is very customizable. A marvel of engineering. Thank you for making it open source. I will implement a custom header handler if these changes are not accepted upstream

**Comment by LucasXu0** [comment]
Thank you for your compliments. 

Yep, I have reviewed your PR and I am considering keeping the previous logic to verify whether the value is an integer or not. So I will close this issue and PR.

**Comment by LucasXu0** [comment]
By the way, you can customize one that supports num type in your project. Just use the same type name to override the existing one.
