### ISSUE TITLE
[Bug] Quick drag selection area issue

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#340]
### Bug Description

Quickly dragging the selection area may cause formatting errors

### How to Reproduce

Quick drag selection

### Expected Behavior

Only selecting does not cause formatting issues

### Operating System

desktop

### AppFlowy Editor Version(s)

master

### Screenshots

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/1d6b1f12-1874-4540-8e91-d7b729f1b79f)

### Additional Context

The following assertion was thrown during a scheduler callback:
'package:appflowy_editor/src/editor/editor_component/service/selection/desktop_selection_service.dart': Failed assertion: line 487 pos 14: 'false': is not true.

When the exception was thrown, this was the stack: 
#2      _DesktopSelectionServiceWidgetState._updateCursorAreas (package:appflowy_editor/src/editor/editor_component/service/selection/desktop_selection_service.dart:487:14)
#3      _DesktopSelectionServiceWidgetState._updateSelection.updateSelection (package:appflowy_editor/src/editor/editor_component/service/selection/desktop_selection_service.dart:152:11)
#4      _DesktopSelectionServiceWidgetState._updateSelection.<anonymous closure> (package:appflowy_editor/src/editor/editor_component/service/selection/desktop_selection_service.dart:165:9)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1223:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#8      _invoke (dart:ui/hooks.dart:142:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#10     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)

**Comment by q200892907** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/91216029-087f-4e21-8418-a9cd1fc52838
