### ISSUE TITLE
[Bug] calling `_deleteRow` on the last row throws `RangeError` 

### ISSUE THREAD

**Issue by sun-jiao** [AppFlowy-IO/appflowy-editor#469]
### Bug Description

```

======== Exception caught by widgets library =======================================================
The following RangeError was thrown building TableView(state: _TableViewState#26442):
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was: 
  TableView TableView:file:///home/sunjiao/StudioProjects/appflowy-editor/lib/src/editor/block_component/table_block_component/table_block_component.dart:150:16
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      TableNode.getColWidth (package:appflowy_editor/src/editor/block_component/table_block_component/table_node.dart:134:20)
#2      TableNode.tableWidth.<anonymous closure> (package:appflowy_editor/src/editor/block_component/table_block_component/table_node.dart:141:31)
#3      ListBase.fold (dart:collection/list.dart:202:22)
#4      TableNode.tableWidth (package:appflowy_editor/src/editor/block_component/table_block_component/table_node.dart:139:44)
#5      _TableViewState.build (package:appflowy_editor/src/editor/block_component/table_block_component/table_view.dart:63:39)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409:27)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297:15)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#10     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#27     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#33     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#39     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#44     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#48     StatelessElement.update (package:flutter/src/widgets/framework.dart:5373:5)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#61     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#71     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#75     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#78     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#80     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#84     StatelessElement.update (package:flutter/src/widgets/framework.dart:5373:5)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#88     Element.updateChildren (package:flutter/src/widgets/framework.dart:3834:32)
#89     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594:17)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#93     StatelessElement.update (package:flutter/src/widgets/framework.dart:5373:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#98     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#100    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#104    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
#105    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
#106    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#107    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#108    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#109    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#110    _invoke (dart:ui/hooks.dart:170:13)
#111    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#112    _drawFrame (dart:ui/hooks.dart:140:31)
====================================================================================================
```

### Operating System

Linux Fedora 38

### AppFlowy Editor Version(s)

newest main

**Comment by sun-jiao** [comment]
Interesting, this only occurs in `_deleteRow`, but not `_deleteCol`.

So when  `_deleteRow` is called on the last row, calling `_deleteCol` recursively will not throw this issue. But I don't think this is a good idea, it's too inelegant.

```dart
void _deleteRow(Node tableNode, int row, EditorState editorState) {
  final transaction = editorState.transaction;

  final int rowsLen = tableNode.attributes[TableBlockKeys.rowsLen],
      colsLen = tableNode.attributes[TableBlockKeys.colsLen];

  if (rowsLen > 1) {
    List<Node> nodes = [];
    for (var i = 0; i < colsLen; i++) {
      nodes.add(getCellNode(tableNode, i, row)!);
    }
    transaction.deleteNodes(nodes);

    _updateCellPositions(tableNode, editorState, 0, row + 1, 0, -1);

    transaction.updateNode(tableNode, {TableBlockKeys.rowsLen: rowsLen - 1});

    editorState.apply(transaction, withUpdateSelection: false);
  } else {
    for (var i = 0; i < colsLen; i++) {
      _deleteCol(tableNode, 0, editorState);
    }
  }
}
```

**Comment by sun-jiao** [comment]
update：

```dart
void _deleteRow(Node tableNode, int row, EditorState editorState) {
  final transaction = editorState.transaction;

  final int rowsLen = tableNode.attributes[TableBlockKeys.rowsLen],
      colsLen = tableNode.attributes[TableBlockKeys.colsLen];
  List<Node> nodes = [];
  for (var i = 0; i < colsLen; i++) {
    nodes.add(getCellNode(tableNode, i, row)!);
  }
  transaction.deleteNodes(nodes);

  _updateCellPositions(tableNode, editorState, 0, row + 1, 0, -1);

  final updateNodeMap = {TableBlockKeys.rowsLen: rowsLen - 1};
  if (rowsLen == 1) {
    updateNodeMap[TableBlockKeys.colsLen] = 0;
  }
  transaction.updateNode(tableNode, updateNodeMap);

  editorState.apply(transaction, withUpdateSelection: false);
}
```
