### ISSUE TITLE
[Bug] Paste rtf file content error

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#580]
### Bug Description

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:appflowy_editor/src/plugins/html/html_document_decoder.dart': Failed assertion: line 57 pos 16: 'false': Unknown node type: 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      DocumentHTMLDecoder._parseElement (package:appflowy_editor/src/plugins/html/html_document_decoder.dart:57:16)
#3      DocumentHTMLDecoder.convert (package:appflowy_editor/src/plugins/html/html_document_decoder.dart:19:19)
#4      Codec.decode (dart:convert/codec.dart:30:34)
#5      htmlToDocument (package:appflowy_editor/src/plugins/html/html_document.dart:13:42)
#6      _extension#0.pasteHtml (package:appflowy_editor/src/editor/editor_component/service/shortcuts/command/paste_command.dart:84:19)
#7      _pasteCommandHandler.<anonymous closure>.<anonymous closure> (package:appflowy_editor/src/editor/editor_component/service/shortcuts/command/paste_command.dart:64:29)

### How to Reproduce

Select all, copy the contents of the rtf file, and then paste it

### Expected Behavior

Can be pasted normally

### Operating System

all

### AppFlowy Editor Version(s)

master

**Comment by q200892907** [comment]
Customize the paste operation and do try catch processing on html
