### ISSUE TITLE
[Bug] assert failure of autoscroll on mobile on empty editor

### ISSUE THREAD

**Issue by gnunicorn** [AppFlowy-IO/appflowy-editor#715]
### Bug Description

We use the editor (thanks by the way for all your great work here!) to create whats-app-style updates in our app. Thus we have the editor centered on the screen start out empty. When we start typing, the `EdgeDraggingAutoScroller` throws an assertion error internally - but everything else seems to work fine.

```dart
E/global.acter.app( 3872):               _dragTargetRelatedToScrollOrigin.size.height': Drag target size is larger than scrollable size, which may cause bouncing
E/global.acter.app( 3872): acter::platform::native: [2024-02-16][11:59:59][acter::platform::native][ERROR] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/global.acter.app( 3872): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/global.acter.app( 3872): #2      EdgeDraggingAutoScroller._scroll (package:appflowy_editor/src/flutter/scrollable_helpers.dart:236:7)
E/global.acter.app( 3872): #3      EdgeDraggingAutoScroller.startAutoScrollIfNecessary (package:appflowy_editor/src/flutter/scrollable_helpers.dart:215:5)
E/global.acter.app( 3872): #4      AutoScroller.startAutoScroll (package:appflowy_editor/src/editor/editor_component/service/scroll/auto_scroller.dart:48:5)
E/global.acter.app( 3872): #5      _MobileScrollServiceState.startAutoScroll (package:appflowy_editor/src/editor/editor_component/service/scroll/mobile_scroll_service.dart:103:19)
E/global.acter.app( 3872): #6      _ScrollServiceWidgetState.startAutoScroll (package:appflowy_editor/src/editor/editor_component/service/scroll_service_widget.dart:172:13)
E/global.acter.app( 3872): #7      _ScrollServiceWidgetState._onSelectionChanged.<anonymous closure>.<anonymous closure> (package:appflowy_editor/src/editor/editor_component/service/scroll_service_widget.dart:109:11)
E/global.acter.app( 3872): #8      new Future.delayed.<anonymous closure> (dart:async/future.dart:427:39)
E/global.acter.app( 3872): #9      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/global.acter.app( 3872): #10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/global.acter.app( 3872): #11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/global.acter.app( 3872): #12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

### How to Reproduce

We only see this on mobile, the Android Emulator in particular when we have `shrinkWrap: true` and the Editor wrapped in:

```dart
MobileToolbarV2(
      toolbarItems: [
        textDecorationMobileToolbarItemV2,
        buildTextAndBackgroundColorMobileToolbarItem(
          textColorOptions: [],
        ),
        headingMobileToolbarItem,
        listMobileToolbarItem,
        linkMobileToolbarItem,
        quoteMobileToolbarItem,
      ],
      editorState: editorState,
      child: MobileFloatingToolbar(
        editorScrollController: editorScrollController,
        editorState: editorState,
        toolbarBuilder: (context, anchor, closeToolbar) {
          return AdaptiveTextSelectionToolbar.editable(
            clipboardStatus: ClipboardStatus.pasteable,
            onCopy: () {
              copyCommand.execute(editorState);
              closeToolbar();
            },
            onCut: () => cutCommand.execute(editorState),
            onPaste: () => pasteCommand.execute(editorState),
            onSelectAll: () => selectAllCommand.execute(editorState),
            onLiveTextInput: null,
            onLookUp: null,
            onSearchWeb: null,
            onShare: null,
            anchors: TextSelectionToolbarAnchors(
              primaryAnchor: anchor,
            ),
          );
        },
        child: AppFlowyEditor(
          // widget pass through
          editable: widget.editable,
          shrinkWrap: widget.shrinkWrap,
          autoFocus: widget.autoFocus,
          header: widget.header,
          // local states
          editorState: editorState,
          editorScrollController: editorScrollController,
          editorStyle: mobileEditorStyle(),
          footer: generateFooter(),
        ),
      ),
    );
```

full code at: https://github.com/acterglobal/a3/blob/18bc72cb5f9d97b2e76771f3a8cd6aa6ec86d69b/app/lib/common/widgets/html_editor.dart

### Expected Behavior

Not seeing any exception

### Operating System

Android Emulator

### AppFlowy Editor Version(s)

2.3.2

**Comment by alexrabin** [comment]
I am having this issue still in 3.3.0

**Comment by k00na** [comment]
Happens for me as well with 4.0.0

**Comment by thomas-tarp** [comment]
Same here with 4.0.0

**Comment by Steph55** [comment]
Still reproducible on **current `main`**, and it is worse than an assertion:
on a slow device the same condition freezes the app until iOS kills it. Here
is the full diagnosis, in case it helps.

## Environment

- `appflowy_editor` **6.1.0**, git dependency pinned to
  `01eccc6ee36bd07698bd80915289fe7070478cd2` — the tip of `main` at the time
  of writing (merge of #1231, 2026-08-06). The original report above was on
  2.3.2, so this has survived every release since.
- Flutter 3.47.1 / Dart 3.13.1, **release** build (asserts off).
- iPhone 8 (`iPhone10,4`), iOS 16.7.12. Not reproducible on recent hardware
  or in the simulator.
- Editor embedded in a fixed-height slot inside a scrolling page, not
  full-screen — this matters, see the viewport table below.

## Symptom

Tapping text in an embedded editor froze the app for more than 10 seconds.
iOS then terminated it:

```
Exception Type:  EXC_CRASH (SIGKILL)
Termination Reason: FRONTBOARD 0x8BADF00D
  scene-update watchdog transgression: exhausted real (wall clock)
  time allowance of 10.00 seconds
Elapsed application CPU time: 11.739 s
```

## Symbolicated main-thread stack

```
dart::Heap::WaitForSweeperTasks(dart::Thread*)      <- blocked here
dart::Heap::AllocateOld(dart::Thread*, long, bool)
dart::Object::Allocate(...)
DRT_AllocateObject
LinkedList.iterator
new _GrowableList.of                                (list copy, per event)
ScrollNotificationObserverState._notifyListeners    scroll_notification_observer.dart:196
NotificationElement.onNotification
NotificationNode.dispatchNotification   x10         (nested scrollables)
ScrollPosition.didEndScroll
ScrollPositionWithSingleContext.jumpTo              <- instant, not animated
ViewportOffset.moveTo
EdgeDraggingAutoScroller._scroll                    scrollable_helpers.dart:376 -> :368
SuspendState._createAsyncStarCallback
tonic::DartMicrotaskQueue::RunMicrotasks            <- entirely in microtasks
```

Meanwhile the worker thread ran `dart::GCSweeper::SweepPage` /
`PageSpace::Sweep` / `ConcurrentSweeperTask::Run`, and the raster and IO
threads were idle. So this is not a rendering stall: the mutator was
waiting on the garbage collector while an unthrottled loop allocated.

## Mechanism

1. `scroll_service_widget.dart:192` starts the auto-scroller with
   `duration: Duration.zero` for every non-drag mobile selection change
   (a plain tap to place the caret).
2. In the vendored `EdgeDraggingAutoScroller._scroll`,
   `scrollable.position.moveTo(newOffset, duration: Duration.zero)` falls
   through to `jumpTo`, so the awaited future is already complete.
3. Line 376, `if (_scrolling) await _scroll();` therefore recurses in the
   **microtask queue**. No frame is ever rendered between iterations, so
   the app cannot paint or process touches.
4. Each iteration's `jumpTo` dispatches a scroll-end notification through
   ~10 nested `NotificationNode`s, and every `ScrollNotificationObserver`
   copies its listener list (`List.of`) on the way. That allocation
   pressure is what eventually blocks the mutator in `AllocateOld`.

## Why only the small screen

The editor is embedded in a slot, so its scroll viewport is small. Measured
with `debugDumpRenderTree`:

| Device | Editor scroll viewport | Default `autoScrollEdgeOffset` = 220 |
|---|---|---|
| Large phone | 267 px | 220 < 267, converges |
| iPhone 8    | ~174 px | **220 > 174, bounces** |

That is exactly the condition this issue reports: the drag target is taller
than the scrollable, so it can never fit and the scroller never settles. On
a fast device the bouncing is absorbed; on an A11 it starves the GC.

Worth noting that the assertion which warned about this — *"Drag target size
is larger than scrollable size, which may cause bouncing"* — was removed in
PR #1056 rather than the bouncing being addressed. Today the condition fails
silently in debug as well as release.

## Suggested direction

`isDragOperation ? const Duration(milliseconds: 2) : Duration.zero` at
`scroll_service_widget.dart:167` looks like the lever. The history already
moves cases off `Duration.zero` one at a time — #1154 for the selection
handles, #1191 for the cursor drag — each time to fix a scrolling bug. The
plain-tap case is the last one left on zero. A non-zero duration routes
`moveTo` through `animateTo`, which yields a frame between iterations, so
the loop can no longer monopolise the microtask queue.

A guard against `dragTarget > viewport` would also be worth restoring in
some form, since that is the condition that makes the loop unable to settle
in the first place.

We worked around it on our side by passing a much smaller
`autoScrollEdgeOffset` and by scrolling the host page so the editor stays
above the keyboard, but that is compensation, not a fix.
