### ISSUE TITLE
[Bug] Getting the `PropertyValueNotifier<Selection?> was used after being disposed` error while opening the drawer.

### ISSUE THREAD

**Issue by divyanshub024** [AppFlowy-IO/appflowy-editor#977]
### Bug Description

Getting the `PropertyValueNotifier<Selection?> was used after being disposed` error while opening the drawer after typing some text.

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
A PropertyValueNotifier<Selection?> was used after being disposed.

Once you have called dispose() on a PropertyValueNotifier<Selection?>, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:183:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:190:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:416:27)
#3      PropertyValueNotifier.value= (package:appflowy_editor/src/editor/util/property_notifier.dart:25:5)
#4      _MobileSelectionServiceWidgetState._updateSelection.<anonymous closure> (package:appflowy_editor/src/editor/editor_component/service/selection/mobile_selection_service.dart:396:36)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1331:11)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#8      _invoke (dart:ui/hooks.dart:312:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#10     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

### How to Reproduce

I have a drawer and Appflow editor on the screen. 

1. Enter some text in the Editor.
2. Open Drawer

### Expected Behavior

Error should not be thrown.

### Operating System

iOS 18.1

### AppFlowy Editor Version(s)

4.0.0

**Comment by asjqkkkk** [comment]
Assign to me
